openapi: 3.0.1
info:
  version: 1.0.0
  title: 掲示板API
paths:
  /threads:
    get:
      parameters:
        -
          name: offset
          in: query
          description: 開始位置
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
        -
          name: limit
          in: query
          description: 表示件数
          required: false
          schema:
            type: integer
            default: 10
            minimum: 1
            maximum: 100
        -
          name: sort
          in: query
          description: 表示順
          required: false
          schema:
            type: string
            enum:
              - creation_desc
              - creation_asc
              - update_desc
              - update_asc
            default: update_desc
      responses:
        200:
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Thread"
components:
  schemas:
    Thread:
      description: スレッド
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          description: スレッドのタイトル
        body:
          type: string
        authorId:
          description: スレッド作成者
          $ref: '#/components/schemas/User'
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
        latestCommentTime:
          type: string
          format: date-time
          description: 最終コメント日時
        creationTime:
          type: string
          format: date-time
          description: 作成日時
        updateTime:
          type: string
          format: date-tiem
          description: 更新日時
        updateVersion:
          type: integer
          description: 現在の更新バージョン
      required:
        - title
        - body
    Tag:
      description: スレッドのタグ
      properties:
        id:
          type: integer
          format: int64
        text:
          type: string
      required:
        - text
    User:
      description: ユーザー情報
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
