@origin = http://localhost:5000

GET {{origin}}/threads?offset=0&limit=10&sort=update_desc

###

POST {{origin}}/threads
Content-Type: application/json

{
  "title": "ほげほげ",
  "name": "ほげ太郎",
  "body": "むかしむかしあるところにいました。",
  "tags": [
    "たぐ1",
    "たぐ2"
  ]
}

###

